### ISSUE TITLE
SocketException is not catching error, if there is no internet

### ISSUE THREAD

**Issue by ShafiMunshi** [EmadBeltaje/flutter_getx_template#17]
I turn off my internet and call some API, It should give me an error " No Internet Connection" , instead it gives me 
"The connection errored: Failed host lookup: 'www.google.com' This indicates an error which most likely cannot be solved by the library."

please, Solve the exception catching error in BaseClient.safeApiCall()

**Comment by EmadBeltaje** [comment]
Hey @ShafiMunshi , thank you for using my template and i'am sorry for late replay, i will check the error and i will update the code asap 🧡

**Comment by EmadBeltaje** [comment]
code has been updated, now the problem is gone 😁
