### ISSUE TITLE
error when tapping notification with app terminated

### ISSUE THREAD

**Issue by tva77** [EmadBeltaje/flutter_getx_template#3]
1- run terminal cmd
`flutter run --release`

2- terminated app;
3- sent fcm message;
4- received notification;
5- tapped notification;
6- app did not started and got error:
 [Awesome Notifications - ERROR]: onActionNotificationMethod is not a valid global or static method. (MethodChannelAwesomeNotifications:?)

**Comment by EmadBeltaje** [comment]
Hey there, 
i just updated the fcm_helper.dart class and now everything should be working fine can you please check it out and tell if everything works fine

**Comment by EmadBeltaje** [comment]
Hey there,
i just updated the fcm_helper.dart class and now everything should be working fine could you please check and confirm if the issue was fixed

**Comment by tva77** [comment]
Thank you!
That error is gone!!
