### ISSUE TITLE
Will you support the Web platform in near future? 

### ISSUE THREAD

**Issue by splex7** [EmadBeltaje/flutter_getx_template#6]
It would be nice if the web version was available as well as iOS and Android.

**Comment by EmadBeltaje** [comment]
yes!
i'am currently working on web support and i will push changes as soon as possible

**Comment by splex7** [comment]
Are you planning to solve the routing issue of the web platform through getx route? Or are you thinking of another alternative?

**Comment by EmadBeltaje** [comment]
> Are you planning to solve the routing issue of the web platform through getx route? Or are you thinking of another alternative?

Hello there, its been a while and I am sorry for that, but I opened an [issue](https://github.com/rafaelsetragni/awesome_notifications/issues/639) and was waiting for [awesome_notifications](https://github.com/rafaelsetragni/awesome_notifications) to support web but it seems that this will not happen at the mean time so i will solve it in a different way, but for this routing problem can you please provide me with details about what is the problem with getx route and navigation in web cause i tried it and everything seems right if you can give me some more details i will upload update the repo
