### ISSUE TITLE
Shared Preferences file missing?

### ISSUE THREAD

**Issue by vnl** [EmadBeltaje/flutter_getx_template#8]
Hi There, 

Absolutely brilliant template and I am learning quite a lot. 

I get the following error with the latest clone:

import 'app/data/local/my_shared_pref.dart';  <-- Missing file

**Comment by cqzongjian** [comment]
+1

**Comment by EmadBeltaje** [comment]
@vnl 
Thanks for your kind words 🧡
sorry about the error i just commited the shared pref class, 
now every thing works fine @cqzongjian
