### ISSUE TITLE
What do you recommend as a good practice to send the fcm token to server?

### ISSUE THREAD

**Issue by evmartinelli** [EmadBeltaje/flutter_getx_template#9]
- Call an api endpont directly
 - Create a controller that call this endpoint?
 - Or another solution?

Thanks in advance!

**Comment by EmadBeltaje** [comment]
i would not recommend making a whole new controller just to perform this action, the simple and good approach would be putting the code inside the fcm helper, inside this function
```dart
static _sendFcmTokenToServer(){
    var token = MySharedPref.getFcmToken();
    // TODO SEND FCM TOKEN TO SERVER
  }
```
and just make this function public, in the template its private bcz i though of sending the token every time it get generated and you can check if the user logged in before you do it or whatever restriction you want..,
so one way to do it if you want to send the token whenever you want and from different places is to make this function public in the fcm helper and put the logic inside of it and also **remove the function call from line (67) in fcm_helper.dart**

and if you also want to check whether the token was sent successfully or not you can do it like this
```dart
static bool sendFcmTokenToServer(){
    var token = MySharedPref.getFcmToken();
    bool tokenSentSuccessfully = false;

    await BaseClient.safeApiCall(
      Constants.todosApiUrl, // url
      RequestType.post,
      onSuccess: (response){ 
        tokenSentSuccessfully = true;
      },
      onError: (error){
        tokenSentSuccessfully = false;
      },
    );
    return tokenSentSuccessfully;
  }
```
hope that helped.🍁

**Comment by EmadBeltaje** [comment]
i would not recommend making a whole new controller just to perform this action, the simple and good approach would be putting the code inside the fcm helper, inside this function
```dart
static _sendFcmTokenToServer(){
    var token = MySharedPref.getFcmToken();
    // TODO SEND FCM TOKEN TO SERVER
  }
```
and just make this function public, in the template its private bcz i though of sending the token every time it get generated and you can check if the user logged in before you do it or whatever restriction you want..,
so one way to do it if you want to send the token whenever you want and from different places is to make this function public in the fcm helper and put the logic inside of it and also **remove the function call from line (67) in fcm_helper.dart**

and if you also want to check whether the token was sent successfully or not you can do it like this
```dart
static Future<bool> sendFcmTokenToServer() async {
    var token = MySharedPref.getFcmToken();
    bool tokenSentSuccessfully = false;

    await BaseClient.safeApiCall(
      Constants.fcmTokenEndpoint, // url
      RequestType.post,
      onSuccess: (response){ 
        tokenSentSuccessfully = true;
      },
    );
    return tokenSentSuccessfully;
  }
```
hope that helped.🍁
